name: wearedesigners
favicon: null
layout_spectrum: 0.8262803319375962
typography_spectrum: 0.9685371948871762
title: We Are Designers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77140863-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a2a2a'
    - '#eaeaea'
    - '#ff102a'
    - '#456c8a'
    - '#b48f08'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.42278556735254824
  rhythmicContrast: 0.25
purpose: []
